# Generated by Django 5.1.1 on 2024-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('disaster_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
